### ISSUE TITLE
Active Actors support

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#25]
Maybe I am unable to find the proper function but I think this one is missing: https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/RigidBodyDynamics.html#active-actors

It would probably improve performance for sleeping objects quite a bit by avoiding to update them.

**Comment by fabmax** [comment]
You are right, I skipped the getActiveActors function becauso both the returned raw pointer / array and the primitive int passed in by reference and used as an output parameter don't map well to Java.

However, it should be possible to write a small wrapper function which maps that to something that can be used from Java.

**Comment by fabmax** [comment]
Was indeed not too hard, it's in the dev branch now. Here is how it works:

```java
    Vector_PxActorPtr activeActors = SupportFunctions.PxScene_getActiveActors(scene);
    int nbActiveActors = activeActors.size();
    for (int i = 0; i < nbActiveActors; i++) {
        PxActor actor = activeActors.at(i);
    }
```

I will wait a bit longer until I publish a new lib version in case more stuff comes up...

**Comment by haubna** [comment]
Perfect, thanks! :)
