### ISSUE TITLE
PxD6Joint inheritance

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#27]
PxD6Joint doesn't inheritate PxJoint as described here: https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/hierarchy.html

**Comment by fabmax** [comment]
You are right, I added the corresponding WebIDL definition (available on dev branch). I will probably publish a new version soon.

**Comment by haubna** [comment]
Thanks! :)
