### ISSUE TITLE
Task :physx-jni:generateJniBindings FAILED

### ISSUE THREAD

**Issue by xhess** [fabmax/physx-jni#3]
Building the bindings throws an error:
> What went wrong:
> Execution failed for task ':physx-jni:generateJniBindings'.
> java.io.FileNotFoundException: physx-jni/src/main/generated/physx/NativeObject.java (file or directory not found)`

I'm not familiar with gradle, but is there an error in _physx-jni/build.gradle.kts_?
The task "generateJniBindings" depends on it self?

**Comment by fabmax** [comment]
The issue was that the generator output directory was missing. Ideally the generator should take care of that but apparently it does not. As a quick fix, until I fixed the generator, I added a check into the build script and let it cvreate the directory if it doesn't exist.

Anyway, should work now

**Comment by xhess** [comment]
Thanks. It works now. You could close the other two issues and keep this one open until you fix the generator.
