### ISSUE TITLE
Extracting contact information

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#30]
Couldn't find a way to implement this behaviour. Would be very useful for playing sounds based on impact force and location.
https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/AdvancedCollisionDetection.html#extracting-contact-information

**Comment by fabmax** [comment]
Alright, version 0.4.15 is up with support for contect point extraction. I also extended the [SimCallbackTest](https://github.com/fabmax/physx-jni/blob/main/physx-jni/src/test/java/de/fabmax/physxjni/SimCallbackTest.java) appropriately.
