### ISSUE TITLE
Passing NULL

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#35]
Couldn't find a way to pass NULL to PxTopLevelFunctions.RevoluteJointCreate()

As described in the official documentation (https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/Joints.html):
"One of the actors must be movable, either a PxRigidDynamic or a PxArticulationLink. The other may be of one of those types, or a PxRigidStatic. Use a NULL pointer here to indicate an implicit actor representing the immovable global reference frame."

**Comment by fabmax** [comment]
Ok, I made the actor0 and actor1 parameters of the createJoint functions nullable, will be included in 0.4.17. As a quickfix it should be possbile to take a PxRigidStatic actor.

**Comment by haubna** [comment]
Thanks! :)
