### ISSUE TITLE
Module Support

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [fabmax/physx-jni#38]
It'd be good to have support for Java 9+ modularity (via `module-info.java`) so people don't need to resort to things like the `extra-java-module-info` gradle plugin.

**Comment by fabmax** [comment]
So far I never used the Java module stuff... Is there an easy way to add the module-info.java while maintaining Java 8 compatibility?

**Comment by Sm0keySa1m0n** [comment]
You could create a multi-release jar (this is also what LWJGL does), which in short means the `module-info.class` file would reside in `META-INF/versions/9` inside the built jar (along with setting `Multi-Release: true` in `MANIFEST.MF`).

**Comment by fabmax** [comment]
I just published version `1.1.0` which is a multi-release jar and contains a module-info
