### ISSUE TITLE
Missing setActorFlag function

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#39]
PxActor is missing the setActorFlag function so you have to retrieve the flags with getActorFlags first, modify them and then set them with setActorFlags which adds quite a bit of JNI overhead.

Function definition can be found here: https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/apireference/files/classPxActor.html

**Comment by fabmax** [comment]
Version `1.1.0` contains the binding to `PxActor.setActorFlag()`
