### ISSUE TITLE
Enabling CCD (Continuous Collision Detection)

### ISSUE THREAD

**Issue by haubna** [fabmax/physx-jni#42]
Is there currently a way to enable CCD? I couldn't find a solution on how to enable the Pair Flag eDETECT_CCD_CONTACT for the Filter Shader.

As described here: https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/AdvancedCollisionDetection.html#continuous-collision-detection

**Comment by fabmax** [comment]
The default filter shader sets the flags present in `word2` of the `PxFilterData`s of the involved collision objects: [https://github.com/fabmax/PhysX/blob/5951e9dbe1e4d003bb7524cfa6aeca19356dc838/physx/source/physxwebbindings/src/PhysXJs.h#L170](https://github.com/fabmax/PhysX/blob/5951e9dbe1e4d003bb7524cfa6aeca19356dc838/physx/source/physxwebbindings/src/PhysXJs.h#L170)

So it should be sufficient to set the `eDETECT_CCD_CONTACT` flag in the simulation filter data of your actors. I'm actually using this in my engine.

**Comment by haubna** [comment]
Perfect, thanks!
