### ISSUE TITLE
Any easy way to visualize a setup?

### ISSUE THREAD

**Issue by salamanders** [fabmax/physx-jni#45]
New to the library, having fun exploring. Is there an easy-ish way to see what is going on, like a no-fancy-materials scene renderer?

**Comment by fabmax** [comment]
Hmm, there is no way to simply toggle between a normal view and a debug view. I guess the easiest way is to simply assign an unlit / blinn-phong material to your meshes, something like this:

```kotlin
// create or load some mesh
val someMesh = colorMesh {
    generate { cube { } }
}

// assign an unlit shader
// or use KslBlinnPhongShader instead of KslUnlitShader to consider scene lighting
someMesh.shader = KslUnlitShader {
    color {
        // use color vertex attribute
        vertexColor()
        // alternatively, use some constant color
        //constColor(Color.GREEN)
    }
}

scene += someMesh
```

**Comment by fabmax** [comment]
Hmm, not really. A pretty easy option would be to use the [PhysX Visual Debugger](https://developer.nvidia.com/physx-visual-debugger) However, that's not yet fully implemented.

**Comment by salamanders** [comment]
Thanks I'll try that when I get back near a PC!
