### ISSUE TITLE
PvdTransport Bindings (PhysX 4)

### ISSUE THREAD

**Issue by Chacty** [fabmax/physx-jni#46]
Hi, is it possibile to bring **DefaultPvdSocketTransportCreate** (and PvdTransport) bindings to PhysX 4 branch? (as already done for PhysX 5)

**Comment by fabmax** [comment]
Yes, that should be possible. You can try to do that yourself: It should be enough to copy the corresponding code to the `PhysXJs.h` and `PhysXJs.idl` files and recompile the library.
