### ISSUE TITLE
Visual Studio 2022 What should I change in the build.gradle.kts?

### ISSUE THREAD

**Issue by jfelrod1960** [fabmax/physx-jni#47]
I have Visual Studio 2022 Community Edition. What should I change in the build.gradle.kts?

**Comment by fabmax** [comment]
VS 2022 should work out of the box. Is there an error message?

**Comment by jfelrod1960** [comment]
I have cmake but not python3.  If this works I will close the issue.  Thanks!

**Comment by jfelrod1960** [comment]
Here is what I'm getting ...

6:48:58 PM: Executing 'buildNativeProject'...

> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Task :generateNativeGlueCode
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\character\PxCharacterController.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\common\PxCommon.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\common\PxCuda.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\cooking\PxCooking.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\extensions\PxExtensions.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\extensions\PxJoint.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\geometry\PxGeometry.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxActor.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxArticulation.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxPhysics.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxScene.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxSceneQuery.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\physics\PxShape.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\PxTopLevel.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\support\PxSupport.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\vehicle\PxVehicle.idl
Parsing C:\Users\JFE\GitHub\physx-jni\physx-jni\src\main\webidl\vehicle\SnippetVehicle.idl

> Task :physx-jni-natives-windows:buildNativeProjectWindows FAILED
MSBuild version 17.4.1+9a89d02ff for .NET Framework
MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
8 actionable tasks: 2 executed, 6 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':physx-jni-natives-windows:buildNativeProjectWindows'.
> Process 'command 'cmake'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 721ms
6:48:59 PM: Execution finished 'buildNativeProject'.

**Comment by fabmax** [comment]
Hmm this line looks a bit suspicious:

`MSBuild version 17.4.1+9a89d02ff for .NET Framework`

It looks like there is only .NET stuff available. Do you have the C++ packages installed (like described [here](https://learn.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170))?

**Comment by fabmax** [comment]
One more thing: The log also says that the project file does not exist. You can try to run `generateNativeProject` before `buildNativeProject` which forces (re-)generating the native project files. Usually this shouldn't be neccessary but maybe something got messed up when running the script without python installed.

**Comment by jfelrod1960** [comment]
That worked @fabmax !!!  I had the C++ packages installed so I did a clean, generateNativeProject and buildNativeProject.  Thank you so much for your help.
