### ISSUE TITLE
PxGjkQuery and PxGjkQueryExt bindings

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [fabmax/physx-jni#57]
Would it be possible to get bindings for `geometry/PxGjkQuery.h` and `extensions/PxGjkQueryExt.h`? They're very useful for calculating contact points in custom geometry.

Thanks :)

**Comment by fabmax** [comment]
Should be relatively straight forward to do, the only thing I need is time ^^

**Comment by fabmax** [comment]
Alright `PxGjkQuery`, `PxGjkQueryExt` and related stuff are included in the latest release: [v2.2.1](https://github.com/fabmax/physx-jni/releases/tag/v2.2.1)
