### ISSUE TITLE
How do I include PhysX on Android in Physics Mod?

### ISSUE THREAD

**Issue by Forever2397** [fabmax/physx-jni#64]
Hello!  i just looked at your github but there is one problem how to include physx jni android library into physics mod

**Comment by fabmax** [comment]
Whoops haven't seen this. Anyway I'm afraid I can't help you. I'm not sure which physics mod you are talking about (the Minecraft thing maybe?). But porting that thing to Android is probably not a trivial task and nothing I can help you with, try asking the mod developer.

**Comment by Forever2397** [comment]
no it's working.  but is there no update for physx jni?

**Comment by Forever2397** [comment]
> Whoops haven't seen this. Anyway I'm afraid I can't help you. I'm not sure which physics mod you are talking about (the Minecraft thing maybe?). But porting that thing to Android is probably not a trivial task and nothing I can help you with, try asking the mod developer.

no bro it's working.  but is there no update for physx jni?
