### ISSUE TITLE
PxTolerancesScale is missing property modification method

### ISSUE THREAD

**Issue by qwq0323** [fabmax/physx-jni#72]
In the PhysX documentation, PxTolerancesScale has two properties, length and speed, but there is no method to modify these two properties in Java.
PhysX document:
`You should set tolerances based on the typical size of objects in your simulation. For example, if you are working with objects of size approximately one meter, but in units of centimeters, you should set the scale as follows:`
```c++
PxFoundation* foundation = ...;
PxTolerancesScale scale;
scale.length = 100;        // typical length of an object
scale.speed = 981;         // typical speed of an object, gravity*1s is a reasonable choice
PxPhysics* p = PxCreatePhysics(PX_PHYSICS_VERSION, *foundation, scale, ...);
```
source code:
``` c++
/**
class PxTolerancesScale
{
public: 

	PxReal	length;

	PxReal	speed;

	PX_INLINE explicit PxTolerancesScale(float defaultLength=1.0f, float defaultSpeed=10.0f);

	PX_INLINE bool isValid() const;

};

PX_INLINE PxTolerancesScale::PxTolerancesScale(float defaultLength, float defaultSpeed) :
	length	(defaultLength),
	speed	(defaultSpeed)
	{
	}
....
```

Java:
```java
public class PxTolerancesScale extends NativeObject {
  public PxTolerancesScale() {
          address = _PxTolerancesScale();
      }
      private static native long _PxTolerancesScale();
....
```
The lack of attribute modification methods prevents me from modifying this scale

**Comment by fabmax** [comment]
length and speed attributes are now exposed (with version 2.4.2), thanks to @TogAr2
